/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FuturePredictionIndexImport } from './routes/future-prediction/index'
import { Route as FuturePredictionSecretInputImport } from './routes/future-prediction/secret-input'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FuturePredictionIndexRoute = FuturePredictionIndexImport.update({
  id: '/future-prediction/',
  path: '/future-prediction/',
  getParentRoute: () => rootRoute,
} as any)

const FuturePredictionSecretInputRoute =
  FuturePredictionSecretInputImport.update({
    id: '/future-prediction/secret-input',
    path: '/future-prediction/secret-input',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/future-prediction/secret-input': {
      id: '/future-prediction/secret-input'
      path: '/future-prediction/secret-input'
      fullPath: '/future-prediction/secret-input'
      preLoaderRoute: typeof FuturePredictionSecretInputImport
      parentRoute: typeof rootRoute
    }
    '/future-prediction/': {
      id: '/future-prediction/'
      path: '/future-prediction'
      fullPath: '/future-prediction'
      preLoaderRoute: typeof FuturePredictionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/future-prediction/secret-input': typeof FuturePredictionSecretInputRoute
  '/future-prediction': typeof FuturePredictionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/future-prediction/secret-input': typeof FuturePredictionSecretInputRoute
  '/future-prediction': typeof FuturePredictionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/future-prediction/secret-input': typeof FuturePredictionSecretInputRoute
  '/future-prediction/': typeof FuturePredictionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/future-prediction/secret-input' | '/future-prediction'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/future-prediction/secret-input' | '/future-prediction'
  id:
    | '__root__'
    | '/'
    | '/future-prediction/secret-input'
    | '/future-prediction/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FuturePredictionSecretInputRoute: typeof FuturePredictionSecretInputRoute
  FuturePredictionIndexRoute: typeof FuturePredictionIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FuturePredictionSecretInputRoute: FuturePredictionSecretInputRoute,
  FuturePredictionIndexRoute: FuturePredictionIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/future-prediction/secret-input",
        "/future-prediction/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/future-prediction/secret-input": {
      "filePath": "future-prediction/secret-input.tsx"
    },
    "/future-prediction/": {
      "filePath": "future-prediction/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
